### ISSUE TITLE
[Bug]: Execution Error after Install

### ISSUE THREAD

**Issue by danielboothcloud** [chrisgrieser/alfred-dock-switcher#1]
### Checklist

- [X] I have updated to the [latest version of this workflow](./releases/latest).
- [X] I am using Alfred 5 or later.

### Alfred version

5.5.1

### macOS version

Sequoia 15.1

### Bug Description

When I install the workflow I can create dock configurations but when I try to switch to one I see the following error:
Error: Error: ls: /Users/danielbooth/.config/alfred-dock-switcher/*.plist: No such file or directory (1)

### To Reproduce

Install workflow
Create Dock configs
Attempt to switch to dock config with _'dock'_ keywoard

### Debugging Log

```Text
what is causing this: [16:30:32.850] ERROR: Dock Switcher[Script Filter] Code 1: /Users/danielbooth/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1FD684F3-6CF2-4F81-A4ED-8FA12AA79277/scripts/select-dock-layout.js: execution error: Error: Error: ls: /Users/danielbooth/.config/alfred-dock-switcher/*.plist: No such file or directory (1)
```

### Workflow Configuration

Default
![CleanShot 2024-12-16 at 16 45 46](https://github.com/user-attachments/assets/4706d1d5-7a7e-4bfa-a299-788a8fd1d886)

**Comment by chrisgrieser** [comment]
Ah, my bad. Fixed in 1.0.2; you will have to save the layouts anew. 

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-dock-switcher/releases/download/1.0.2/alfred-dock-switcher.alfredworkflow
